services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - "443:443"
    volumes:
      - wp-data:/var/www/html
    networks:
      - inception
    depends_on:
      - wordpress

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    restart: unless-stopped
    env_file: .env
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - inception

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress

    restart: unless-stopped
    volumes:
      - wp-data:/var/www/html
    networks:
      - inception
    expose:
      - "9000"
    environment:
      - WORDPRESS_DB_NAME=${DB_NAME}
      - WORDPRESS_DB_USER=${DB_USER}
      - WORDPRESS_DB_PASSWORD=${DB_PASSWORD}
      - WORDPRESS_DB_HOST=mariadb:3306
    depends_on:
      - mariadb

volumes:
  wp-data:
  db-data:

networks:
  inception:
    driver: bridge
