services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    image: nginx
    restart: unless-stopped
    ports:
      - "443:443"
    volumes:
      - wp-data:/var/www/html
    networks:
      - inception
    depends_on:
      - wordpress

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    image: mariadb
    restart: unless-stopped
    env_file: .env
    
    volumes:
      - db-data:/var/lib/mysql
    # ports:
    #   - "3306:3306"
    networks:
      - inception
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    image: wordpress
    restart: unless-stopped
    volumes:
      - wp-data:/var/www/html
    networks:
      - inception
    # expose:
    # - "9000"
    env_file: .env
    environment:
      - WORDPRESS_DB_NAME=${DB_NAME}
      - WORDPRESS_DB_USER=${DB_USER}
      - WORDPRESS_DB_PASSWORD=${DB_PASSWORD}
      - WORDPRESS_DB_HOST=mariadb
      - WP_ADMIN_USER=${WP_ADMIN_USER}
      - WP_ADMIN_PASSWORD=${WP_ADMIN_PASSWORD}
      - WP_ADMIN_EMAIL=${WP_ADMIN_EMAIL}
      - WP_SITE_URL=${WP_SITE_URL}
      - WP_SITE_TITLE=${WP_SITE_TITLE}
      - WP_USER2_NAME=${WP_USER2_NAME}
      - WP_USER2_EMAIL=${WP_USER2_EMAIL}
      - WP_USER2_PASSWORD=${WP_USER2_PASSWORD}
    depends_on:
      - mariadb

volumes:
  wp-data:
    driver: local
    driver_opts:
      type: none
      device: ${HOME}/data/wp-data
      o: bind
  db-data:
    driver: local
    driver_opts:
      type: none
      device: ${HOME}/data/db-data
      o: bind

networks:
  inception:
    driver: bridge
