CREATE DATABASE IF NOT EXISTS wpdb;
CREATE USER IF NOT EXISTS 'kvoznese'@'%' IDENTIFIED BY '123';
GRANT ALL PRIVILEGES ON wpdb.* TO 'kvoznese'@'%';
ALTER USER 'root'@'localhost' IDENTIFIED BY 'rootpass';
FLUSH PRIVILEGES;
